[program:posretail-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/posretail/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=bang1436
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/posretail/storage/logs/worker.log
stopwaitsecs=3600

[program:posretail-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/posretail/artisan schedule:work
autostart=true
autorestart=true
user=bang1436
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/posretail/storage/logs/scheduler.log
